env:
  node: true
  browser: true
  jest/globals: true
plugins:
  - prettier
  - react
  - jsx-a11y
  - jest
extends:
  - eslint:recommended
  - standard
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - prettier
  - prettier/react
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true
  sourceType: module
settings:
  import/core-modules:
    - react
  react:
    version: detect
rules:
  react/prop-types: off
  prettier/prettier: error
  no-unused-vars:
    - error
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  no-console:
    - off
  no-var:
    - error
  prefer-const:
    - error
  prefer-rest-params:
    - warn
  prefer-spread:
    - warn
  prefer-template:
    - warn
  camelcase:
    - warn
